
config {
  type: "table",
  schema: dataform.projectConfig.vars.silver_dataset_name,
  description: "Cleaned version of users table.",
  assertions: {
    rowConditions: ["user_tenure > 12"]
  },
  columns: {
    user_id: "User ID",
    age: "Age",
    creation_date: "Date creation",
    user_tenure: "User tenure"
  }
}

select
  id as user_id,
  age,
  creation_date,
  round(timestamp_diff(current_timestamp(), creation_date, day)/365) as user_tenure
from
  ${ref("users")}